############################################################
#
#  Runtime Environment for running nextflow in a container.
#  Nextflow is expected to launch containers on the host
#  using the CONTAINER_HOST socket.
#
############################################################

FROM quay.io/podman/stable:v5

RUN dnf install -y java-21-openjdk-headless

USER podman
WORKDIR /home/podman
RUN mkdir bin &&  curl -s https://www.nextflow.io/releases/v25.10.4/nextflow?a=install -o bin/nextflow && chmod +x bin/nextflow && bin/nextflow info

# let nextflow launch containers with the socket instead of libpod.
# we will also need to bind mount the user socket on the host to this path.
# this way nextflow containers will be able to use the host image cache instead
# of pulling the container images inside the nextflow container every single time.
# To make this work in a rootless environment, one would need to use the following podman run options when launching this container
# --security-opt label=type:container_runtime_t
# -v ${XDG_RUNTIME_DIR}/podman/podman.sock:/run/podman/podman.sock:z # mount the host user socket to the container
# --userns=keep-id:uid=1000,gid=1000 #map host user to podman(1000) inside the container
ENV CONTAINER_HOST=unix:///run/podman/podman.sock

# we don't want nextflow to try to update itself on every run.
# use whatever version is installed in the container.
ENV NXF_DISABLE_CHECK_LATEST=true
ENV NXF_OFFLINE=true

COPY --chown=podman nextflow /nextflow
WORKDIR /nextflow
